import './globals.css'
import { IBM_Plex_Sans } from 'next/font/google'

import About from './components/About'

const ibm_plex_sans = IBM_Plex_Sans({ subsets: ['latin'], weight: ["300"] })

export const metadata = {
    title: 'Rebeca Melo - Portfolio',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={ibm_plex_sans.className}>
                <About />
                {children}
            </body>
        </html>
    )
}
