import './globals.css'
import './scroll.css'
import { Solway } from 'next/font/google'

import About from './components/About'

const solway = Solway({ subsets: ['latin'], weight: ["300", "400", "500"] })

export const metadata = {
    title: 'Rebeca Melo - Portfolio',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={solway.className}>
                <About />
                {children}
            </body>
        </html>
    )
}
